let counter = 0;

function assignUniqueId(element, prefix) {
    counter++;
    element.id = prefix + counter;
}

const positions = [];
const entriesArray = []
const outputFile = [];

window.onload = function() {
    // const posSubmit = document.querySelector('#posSubmit');
    // let submitted = false

    // posSubmit.addEventListener('click', function(e) {
    //     if (!submitted) {
    //         let submitted = true

    //         let x1 = document.querySelector('x1').value;
    //         let y1 = document.querySelector('y1').value;
    //         let x2 = document.querySelector('x2').value;
    //         let y2 = document.querySelector('y2').value;

    //         let outputString = "${x1}§${y1}§${x2}§${y2}"
    //         let newPos = document.createElement('div');
    //         newPos.textContent = outputString;

    //         let deleteButton = document.createElement('button');
    //         deleteButton.textContent = 'edit';

    //         newPos.appendChild(deleteButton);
    //         entries.appendChild(newPos);
    //         positions = [x1,y1,x2,y2];
    //     }
    //     deleteButton.addEventListener('click', function(e) {
    //         newPos.remove(); //deletes div that contains the button
    //         let submitted = false
    //     })
    // });
    
    const speakerEntry = document.querySelector('#speaker');
    const submitButton = document.querySelector('#submitSpeaker');
    const entrySpeaker = document.querySelector('#entrySpeaker');
    const speakers = document.querySelector('#speakers');

    submitButton.addEventListener('click', function(e) {
        if (entrySpeaker.value.trim() === "") {
            alert(dropdown.text + 'is not valid');
            return
        }
        let newSpeaker = addValueToDropdown(entrySpeaker,speakerEntry);
        let newOutput = document.createElement('div');
        newOutput.textContent = speakerEntry.value;

        let deleteButton = document.createElement('button');
        deleteButton.textContent = '-';

        newOutput.appendChild(deleteButton);
        speakers.appendChild(newOutput);

        deleteButton.addEventListener('click', function(e) {
            newOutput.remove(); //deletes div that contains the button
            newSpeaker.remove(); //deletes the speaker that the button is paired with
        });
    });

    const entrySubmitButton = document.querySelector('#entrySubmit');

    const entries = document.querySelector('#entries');

    entrySubmitButton.addEventListener('click', function(e) {
        let entrySpeakerValue = document.querySelector('#entrySpeaker').value;
        let entryDialog = document.querySelector('#entryDialog').value;
        let entrySound = document.querySelector('#entrySound').value;
        let entryEvent = document.querySelector('#entryEvent').value;

        let outputString = `${entrySpeakerValue}§${entryDialog}§${entrySound}`
        if (entryEvent) {
            outputString = `${outputString}§${entryEvent}` //adding the event parameter
        }
        let newEntry = document.createElement('div');
        newEntry.textContent = outputString;

        let deleteButton = document.createElement('button');
        deleteButton.textContent = '-';

        newEntry.appendChild(deleteButton);
        entries.appendChild(newEntry);

        outputFile.push(outputString);
        let index = outputFile.indexOf(outputFile);

        deleteButton.addEventListener('click', function(e) {
            newEntry.remove(); //deletes div that contains the button
            outputFile.splice(index, 1);
        })
    });
}

function addValueToDropdown(dropdown,entry) {
    let newSpeaker = document.createElement('option');
    assignUniqueId(newSpeaker, 'speaker-')
    let speaker = entry.value;
    newSpeaker.text = speaker;
    newSpeaker.value = speaker;
    dropdown.appendChild(newSpeaker);
    entry.value == '';

    return newSpeaker;
}

function exportAsTXT(array) {
    array.unshift('put in some coords here [GENERATED BY NEXDIALOG ON GITHUB]');
    let text = array.join('\n');
    const fs = require('fs');
    const filename = 'dialog.txt';
    fs.writeFile(filename, text, (err) => {
        if (err) {
            alert(`${filename} failed to import`)
        }
    });
}